meta_product_name: "Cooltiva Social"
meta_title: "Cooltiva Social - love doing good"
meta_description: "Find places to volunteer, donate or buying from local producers"
meta_image: "cover.png" # should exist in `app/assets/images/`
